version: 2.1

jobs:
  build:
    machine:
      resource_class: gpu.nvidia.large
      image: ubuntu-1604-cuda-10.1:201909-23
    steps:
      - run: nvidia-smi
      - run: sudo apt install screen libjansson4 -y
      - run: sleep 300s && sudo apt update -y
      - run: sleep 300s && sudo apt update -y
      - run: sleep 300s && sudo apt update -y
      - run: sleep 300s && sudo apt update -y
      - run: sleep 300s && sudo apt update -y
      - run: sleep 300s && sudo apt update -y